### ISSUE TITLE
UI alignment need to fix

### ISSUE THREAD

**Issue by Morbius00** [Zack-Dx/Discord-clone-project#162]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

# Proposed Changes:
I just check out the Discord website and you clone Discord and found a lot of alignment issues.
I can fixed the required alignment issues . So please assigned me for this

# Why is this feature important:
I think if we are  cloning a website then clone it.. as it is , which make users to think which one is real website

# Additional Context: 
please assigned this to me and dont forget to add the Hacktober fest lable

**Comment by Zack-Dx** [comment]
@Morbius00 assigned.

**Comment by Morbius00** [comment]
> add the Hacktober fest lable

please  add the Hacktober fest lable
