### ISSUE TITLE
Changes in the support page

### ISSUE THREAD

**Issue by psood708** [Zack-Dx/Discord-clone-project#184]
#Proposed Changes:
Alignment of the Help Center text initially on the page
The max width of the page
#Why is this feature important:
This is important as for UI/UX of the page

**Comment by 0nikhilkumar** [comment]
Sir as I am hacktoberfest'23 participant please see and merge and give the label "hacktoberfest-accepted" its please contibution and One count is also included in hacktoberfest'23 @Zack-Dx @Zack-Dx
