### ISSUE TITLE
Url Not Functional

### ISSUE THREAD

**Issue by kiongosss** [Zack-Dx/Discord-clone-project#191]
URL: https://discord-clone-project.netlify.app/ - Not Found - Request ID: 01GMX2FRA6VECGQFV81RBRS0F3
![image](https://user-images.githubusercontent.com/80756727/209151665-3e37d98a-40e7-445c-a81b-c830d8321ff9.png)

**Comment by Zack-Dx** [comment]
@kiongosss Fixed Thanks!
