### ISSUE TITLE
Fonts don't look the same as on Discord's website

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [Zack-Dx/Discord-clone-project#38]
#Proposed Changes: Change the font family and use font query in CSS to make the font accessible for everyone.

#Why is this feature important: fonts play a **major role** in the UI of the website

#Additional Context: I @Shivangbhatnagar237 can fix this issue, this issue will bring other text-positioning issues under it as well
![disc1](https://user-images.githubusercontent.com/47966497/194137027-9fc90bc5-6220-47d0-9001-03e68c3e95b9.PNG)
![disc2](https://user-images.githubusercontent.com/47966497/194137215-17b7b6ae-271e-44c6-bc50-f4d02f258ea2.PNG)
I've uploaded both images for comparison (1st image - Discord website, 2nd image - Discord-Clone)

**Comment by Shivangbhatnagar237** [comment]
@Zack-Dx please assign me this issue under hacktoberfest, I can solve it.

**Comment by Zack-Dx** [comment]
@Shivangbhatnagar237 Sure. go ahead

**Comment by Shivangbhatnagar237** [comment]
@Zack-Dx I've created a PR
