### ISSUE TITLE
Addition of link and hovering effect.

### ISSUE THREAD

**Issue by AnushkaMittal21** [Zack-Dx/Discord-clone-project#51]
#Proposed Changes: Want to add the link to download the discord app on both the button on the page "Download for windows"?
Also need to add a hovering effect on the button "Download for windows" (below one).

#Why is this feature important: It will make the clone more like the actual website.

#Additional Context:

**Comment by AnushkaMittal21** [comment]
Please assign this to me.

**Comment by Zack-Dx** [comment]
@AnushkaMittal21 Go ahead.
