### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by grraghav120** [Zack-Dx/Discord-clone-project#56]
**Describe the bug**
open button is not working after click

**Expected behavior**
open the discord link

**Screenshots**
This button
![image](https://user-images.githubusercontent.com/96789493/194243499-20222d08-e2d2-417d-9281-8adca2b610c5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by grraghav120** [comment]
I want to work on

**Comment by tech0x10** [comment]
it isn't a bug, the maintainer hasn't put any link in the anchor tag

**Comment by Zack-Dx** [comment]
> it isn't a bug, the maintainer hasn't put any link in the anchor tag

@tech0x10 right!

@grraghav120 yes sure.
